version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: install_dependencies
      timeout: 100
      runas: root
    - location: start_server
      timeout: 100
      runas: root
